package model.board;

/**
 * Created by Sachit on 4/19/2014.
 */

import model.tiles.IrrigationTileComponent;
import model.tiles.Tile;

import java.util.ArrayList;
import java.util.List;

/**The purpose of this class is to create our board. It is a very specific
 * class, created without almost any reusability in mind. It is simply an
 * easier way to delegate board creation to another class from the model
 * so that all of the code doesn't end up somewhere else.
 */
public class BoardCreator {
    private JavaBoard board;

    public JavaBoard createBoard() {
        board = new JavaBoard();

        List<Directions> directions = new ArrayList<Directions>();
        HexLocation loc;
        Space space;
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.placeIrrigationTileComponent(loc, new IrrigationTileComponent(new Tile(1)));
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.placeIrrigationTileComponent(loc, new IrrigationTileComponent(new Tile(1)));
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.placeIrrigationTileComponent(loc, new IrrigationTileComponent(new Tile(1)));
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToLowlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.NORTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTH);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHEAST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);
        directions.add(Directions.SOUTHWEST);
        loc = new HexLocation(new ArrayList<Directions>(directions));
        space = new JavaSpace();
        board.placeSpace(loc, space);
        board.addToHighlands(loc);


        return board;
    }
}
